export class Api {
  public static readonly WEATHER_API =
    'https://zhwnlapi.etouch.cn/Ecalender/api/v2/weather?date=20240523&app_key=99817749'
  public static readonly SELECT_CITY_API =
    'http://zhwnlapi.etouch.cn/Ecalender/api/city?lon=&app_ts=1502957577098&app_key=99817749&device_id=29c82fbe10331817eb2ba134d575d541&city_key=101210101&ver_name=6.9.6&uid=&keyword=&ver_code=716&channel=own&auth_token=eyJhY2N0ayI6IiIsInVwIjoiQU5EUk9JRCIsImRldmljZSI6IlNNLUc5NTUwMzUyNTYyMDc3MjY0MzM0In0%3D&lat=&type=hotV2&devid=a47cc0669be48a6b49aba18d1c42e200&os_version=70'
  public static readonly SEARCH_CITY_API =
    'https://zhwnlapi.etouch.cn/Ecalender/api/city?lon=&app_ts=1502957830998&app_key=99817749&foreign=true&device_id=29c82fbe10331817eb2ba134d575d541&ver_name=6.9.6&ver_code=716&uid=&channel=own&auth_token=eyJhY2N0ayI6IiIsInVwIjoiQU5EUk9JRCIsImRldmljZSI6IlNNLUc5NTUwMzUyNTYyMDc3MjY0MzM0In0%3D&lat=&type=search&devid=a47cc0669be48a6b49aba18d1c42e200&os_version=70'
  public static readonly LOCATION_API =
    'https://apis.map.qq.com/ws/geocoder/v1/?key=E4DBZ-MKZW3-QSC3L-YNQNK-IQI3K-ERBDW'
}