export class RouterConstants {
  public static readonly SPLASH_PAGE = 'SplashPage'
  public static readonly WEATHER_MAIN_PAGE = 'WeatherMainPage'
  public static readonly SELECT_CITY_PAGE = 'SelectCityPage'
  public static readonly WEATHER_PREVIEW_PAGE = 'WeatherPreviewPage'
  public static readonly WEATHER_CARD_SORT_PAGE = 'WeatherCardSortPage'
  public static readonly WEATHER_BG_LIST_PAGE = 'WeatherBgListPage'
  public static readonly WEATHER_BG_EDIT_PAGE = 'WeatherBgEditPage'
}